### ISSUE TITLE
SmarAct releasing motors with new sensor types

### ISSUE THREAD

**Issue by keenanlang** [epics-motor/motorSmarAct#3]
The MCS driver, on creation, sends the command "GST" to get the axis' sensor type and then checks that value against a list of known values to see if it is dealing with a rotary motor or a linear one. Unfortunately, SmarAct is still releasing new motors that report new sensor types that aren't included in the list. Linear motors will default to correct operation, but new rotary motors don't work with the driver.

We could add the new sensor types to the list in the driver, but that would just be kicking the problem down the road a bit. I suggest switching the code to just send the command "GA" or "GP" and check which command sends a readable reply and which sends error code 143.

**Comment by kmpeters** [comment]
That seems like it would be a better approach.  Shall I create a branch for this or have you already begun modifying the driver?

**Comment by kmpeters** [comment]
Pinging @keenanlang

**Comment by kmpeters** [comment]
Fixed by #4
